title: SF Crime Data Analysis
description: A data-driven exploration of crime patterns in San Francisco
baseurl: ""
url: "https://charlesdark.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - data/*.csv
  - scripts/
  - requirements.txt
